name: FTP Deploy Locaweb
  on: push
    jobs:
      deploy:
        name: Deploy
          runs-on: ubuntu-latest
          steps:
          - uses: locaweb/ftp-deploy@1.0.0

          - name: FTP Deploy Locaweb
            uses: locaweb/ftp-deploy@1.0.0
            with:
              host: ftp.armazemnet.com.br 
              user: armazemnet1
              password: ido@2021
              localDir: "dist"
